app-gest-contr/app/user/forms.py
from flask_wtf import FlaskForm, Form
from wtforms import SubmitField, DateField, HiddenField ,StringField, SelectField, PasswordField, DateTimeField, validators
from wtforms.validators import DataRequired, InputRequired, Email, Length

class RegistroMulta(Form):
   user_id=HiddenField("user_id",validators=[DataRequired()])
   contrato_id=HiddenField("contrato_id", validators=[DataRequired()])
   glosa=StringField("glosa",validators=[DataRequired()])
   monto=StringField("monto",validators=[DataRequired()])
   statusMulta=StringField("statusMulta",validators=[DataRequired()])


class RegistroFactura(Form):
   user_id=HiddenField("user_id",validators=[DataRequired()])
   contrato_id=HiddenField("contrato_id", validators=[DataRequired()])
   docFactura=StringField("docFactura", validators=[DataRequired()])
   statusFactura=StringField("statusFactura", validators=[DataRequired()])

app-gest-contr/app/user/views.py
from datetime import date, datetime
from flask import Blueprint, render_template, request, flash
from flask.helpers import url_for
from werkzeug.utils import redirect
from flask_login import login_required, current_user
import datetime
import sys


from app.actiondb import ModeloBaseDB
from app.auth.models import Contrato, Logs, User,Multas,Facturas
from app.indicadores import Indicadores
from app.user.forms import RegistroMulta, RegistroFactura
from app.upload import Archivos
from app.logs import LogsTareas
user=Blueprint("user",__name__,template_folder="templates")


@user.route("/dashboarduser", methods=["GET","POST"])
@login_required
def Dashboard():
    total_contratos=ModeloBaseDB.seleccionarItsId(Contrato,current_user.id)
    total_logs=ModeloBaseDB.seleccionarItsId(Logs,current_user.id)
    total_multas=ModeloBaseDB.seleccionarUserId(Multas,current_user.id)
    total_facturas=ModeloBaseDB.seleccionarUserId(Facturas,current_user.id)

    return render_template("usrseguircontratos.html",
    total_contratos=total_contratos,
    total_logs=total_logs,
    total_multas=total_multas,
    total_facturas=total_facturas)


@user.route("/usrcontrato/<id>",methods=["GET","POST"])
@login_required
def AccionesContrato(id):
    modelo_contrato=ModeloBaseDB.seleccionarId(Contrato,id)
    id_its=ModeloBaseDB.seleccionarId(Contrato,id).its_id
    its=ModeloBaseDB.seleccionarId(User,id_its)

    return render_template("usrcontrato.html", 
    its=its,
    modelo_contrato=modelo_contrato)



@user.route("/usrmulta/<id>", methods=["GET","POST"])
@login_required
def Multa(id):
    return render_template("multas.html",contrato_id=id)


@user.route("/registromulta", methods=["GET","POST"])
@login_required
def RegistrarMulta():
    formulario_multa=RegistroMulta(request.form)
    if request.method=="POST":

        registro_multas=Multas(
            user_id=formulario_multa.user_id.data,
            contrato_id=formulario_multa.contrato_id.data,
            glosa=formulario_multa.glosa.data,
            monto=formulario_multa.monto.data,
            statusMulta=formulario_multa.statusMulta.data
            
        )
        ModeloBaseDB.guardar(registro_multas)

        usuario_log="{} {}".format(current_user.nombresUser, current_user.apellidosUser)
        tiempo_creacion="{} {}".format(str(datetime.date.today()),str(datetime.datetime.now().time().strftime("%H:%M:%S")))        
        log_multa=LogsTareas(usuario_log,tiempo_creacion,None)
        log_multa=log_multa.logRegistrarMulta()
        print("[!] Multa guardada",file=sys.stderr)

        log=Logs(current_user.id,
        tiempo_creacion,
        log_multa
        )

        ModeloBaseDB.guardar(log)
        print("[!] Log almacenado",file=sys.stderr)

        flash("Multa registrada exitosamente")
    return redirect(url_for("user.Dashboard"))


@user.route("/usrfactura/<id>", methods=["GET","POST"])
@login_required
def Factura(id):
    return render_template("facturas.html", contrato_id=id)

@user.route("/registrarfactura", methods=["GET","POST"])
@login_required
def RegistrarFactura():
    formulario_factura=RegistroFactura(request.form)
    if request.method=="POST":
        registro_factura=Facturas(
            formulario_factura.user_id.data,
            formulario_factura.contrato_id.data,
            formulario_factura.docFactura.data,
            formulario_factura.statusFactura.data,
            str(datetime.datetime.now())
        )

        print(formulario_factura.user_id.data,
            formulario_factura.contrato_id.data)

        ModeloBaseDB.guardar(registro_factura)
        usuario_log="{} {}".format(current_user.nombresUser, current_user.apellidosUser)
        tiempo_creacion="{} {}".format(str(datetime.date.today()),str(datetime.datetime.now().time().strftime("%H:%M:%S")))        

        log_factura=LogsTareas(usuario_log,tiempo_creacion,formulario_factura.docFactura.data)
        log_factura=log_factura.logRegistrarFactura()

        log=Logs(current_user.id,
        tiempo_creacion,
        log_factura
        )

        ModeloBaseDB.guardar(log)
       

        
        flash("Factura Registrada exitosamente")
        return redirect(url_for("user.Dashboard"))


@user.route("/editarfactura/<id>", methods=["GET","POST"])
@login_required
def EditarFactura(id): 
    factura_a_editar=ModeloBaseDB.seleccionarId(Facturas,id)
    
    return render_template("editarfactura.html", factura_a_editar=factura_a_editar)


@user.route("/actualizarfactura/<id>", methods=["GET","POST"])
@login_required
def ActualizarFactura(id):
    formulario_edicion=RegistroFactura(request.form)
    if request.method=="POST":
        
        ModeloBaseDB.editarUsuario(Facturas,id,formulario_edicion)
        usuario_log="{} {}".format(current_user.nombresUser, current_user.apellidosUser)
        tiempo_creacion="{} {}".format(str(datetime.date.today()),str(datetime.datetime.now().time().strftime("%H:%M:%S")))        

        log_edit_factura=LogsTareas(usuario_log,tiempo_creacion,formulario_edicion.docFactura.data)
        log_edit_factura=log_edit_factura.logEditarFactura()
        print(log_edit_factura,file=sys.stderr)
        log=Logs(current_user.id,
        tiempo_creacion,
        log_edit_factura)
        ModeloBaseDB.guardar(log)

        flash("Factura editada Satisfactoriamente")
    return redirect(url_for("user.Dashboard"))


@user.route("/editarmulta/<string:id>", methods=["GET","POST"])
@login_required
def EditarMulta(id):
    multa_a_editar=ModeloBaseDB.seleccionarId(Multas,id)
    return render_template("editarmulta.html", multa_a_editar=multa_a_editar)


@user.route("/actualizarmulta/<id>", methods=["GET","POST"])
@login_required
def ActualizarMulta(id):
    formulario_edicion=RegistroMulta(request.form)
    if request.method =="POST":
        ModeloBaseDB.editarUsuario(Multas,id,formulario_edicion)
        flash("Multa editada satisfactoriamente")
        return redirect(url_for("user.Dashboard"))

app-gest-contr/app/user/templates/editarfactura.html
{% extends 'layout.html' %}

{% block body %}





<h1 style="text-align: center;">Facturas: cambio de estado</h1>

<div class="container-login">
    <form class="form-group" action="/user/actualizarfactura/{{ factura_a_editar.id }}" method="post">
        
        <div class="form-input">
         
            <input type="hidden" id="user_id" name="user_id" value="{{ current_user.id}}">
        </div>

        <div class="form-input">
            
            <input type="hidden" id="contrato_id" name="contrato_id" value="{{ factura_a_editar.contrato_id }}">
        </div>
        <div class="form-input">
            <label class="form-label"> <h2>Número documento Factura</h2></label>
            <input class="form-control" type="text" id="docFactura" name="docFactura" value={{factura_a_editar.docFactura}} readonly="readonly">
        </div>
        <div class="form-group">
            <label class="form-label"> <h2>Estado de la Factura:</h2><h4 style="margin: 0;">{{factura_a_editar.statusFactura}}</h4></label>

            <p>
            <input type="radio" name="statusFactura" value="REGISTRADA"> Factura Registrada <br>
            <input type="radio" name="statusFactura" value="RECHAZADA"> Factura Rechazada <br>
            <input type="radio" name="statusFactura" value="ACEPTADA"> Factura Aceptada 
        </p>
        </div>
        <div class="container-logo">
            <button class="ingresar" type="submit">INGRESAR</button>
        </div>
    </form>
</div>
<div class="container-logo">
    <a href="/user/dashboarduser">
        <div class="ingresar">
            VOLVER
        </div>
    </a>
</div>

-->


{% endblock %}

app-gest-contr/app/user/templates/editarmulta.html
{% extends 'layout.html' %}


{% block body %}

<h1 style="text-align: center;">Editar multas</h1>
<div class="container-login">
    <form class="form-group" action="/user/actualizarmulta/{{multa_a_editar.id}}" method="post">
        
        <div class="form-input">
         
            <input type="hidden" id="user_id" name="user_id" value="{{ current_user.id }}">
        </div>

        <div class="form-input">
            
            <input type="hidden" id="contrato_id" name="contrato_id" value="{{ contrato_id }}">
        </div>
        <div class="form-input">
            <label><h4>Monto de la sanción o multa (UTM)</h4></label>
            <input class="form-control" value="{{multa_a_editar.monto}}" type="text" id="monto" name="monto" placeholder="Monto UTM" readonly="readonly">
        </div>
        <br>
        <hr>
        <div class="form-input">
            <label><h4>Glosa o detalle de multa</h4></label>
            <p> {{ multa_a_editar.glosa}}
            </p>
            <input class="form-control" value="{{multa_a_editar.glosa}}" type="hidden" id="glosa" name="glosa" readonly="readonly">

            
        </div>
        <hr>
        
        <div class="form-input">
            <label><h4>Estado de multa</h4></label>
            <p> {{ multa_a_editar.statusMulta }}</p>
            <hr>
            <h4> Cambiar estado a: </h4>
            <p>
            <input type="radio" name="statusMulta" value="CURSADA" required> Multa Cursada <br>
            <input type="radio" name="statusMulta" value="NOTIFICADA"> Multa Notificada <br>
            <input type="radio" name="statusMulta" value="IMPUGNADA"> Multa Impugnada <br>
            <input type="radio" name="statusMulta" value="APELADA"> Multa Apelada <br>
            <input type="radio" name="statusMulta" value="EJECUTADA"> Multa Ejecutada <br>
        </p>
        </div>
        <div class="container-logo">
            <button class="ingresar" type="submit">INGRESAR</button>
        </div>
        
    </form>
</div>

<div class="container-logo">
    <a href="/user/dashboarduser">
        <div class="ingresar">
            VOLVER
        </div>
    </a>
</div>





{% endblock %}

app-gest-contr/app/user/templates/facturas.html
{% extends 'layout.html' %}


{% block body %}
<h1 style="text-align: center;">Facturas</h1>
<div class="container-login">
    <form class="form-group" action="{{url_for('user.RegistrarFactura')}}" method="post">
        
        <div class="form-input">
         
            <input type="hidden" id="user_id" name="user_id" value="{{ current_user.id }}">
        </div>

        <div class="form-input">
            
            <input type="hidden" id="contrato_id" name="contrato_id" value="{{ contrato_id }}">
        </div>
        <div class="form-input">
            <label class="form-label"> <h2>Número documento Factura</h2></label>
            <input class="form-control" type="text" id="docFactura" name="docFactura">
        </div>
        <div class="form-group">
            <label class="form-label"> <h2>Estado de la Factura</h2></label>
            <p>
            <input type="radio" name="statusFactura" value="REGISTRADA" required> Factura Registrada <br>
            <input type="radio" name="statusFactura" value="RECHAZADA"> Factura Rechazada <br>
            <input type="radio" name="statusFactura" value="ACEPTADA"> Factura Aceptada <br>
        </p>
        </div>
        <div class="container-logo">
            <button class="ingresar" type="submit">INGRESAR</button>
        </div>
    </form>
</div>
<div class="container-logo">
    <a href="/user/dashboarduser">
        <div class="ingresar">
            VOLVER
        </div>
    </a>
</div>




{% endblock %}

app-gest-contr/app/user/templates/multas.html
{% extends 'layout.html' %}


{% block body %}
<h1 style="text-align: center;">Multas</h1>
<div class="container-login">
    <form class="form-group" action="{{url_for('user.RegistrarMulta')}}" method="post">
        
        <div class="form-input">
         
            <input type="hidden" id="user_id" name="user_id" value="{{ current_user.id }}">
        </div>

        <div class="form-input">
            
            <input type="hidden" id="contrato_id" name="contrato_id" value="{{ contrato_id }}">
        </div>
        <div class="form-input">
            <label><h4>Monto de la sanción o multa (UTM)</h4></label>
            <input class="form-control" type="text" id="monto" name="monto" placeholder="Monto UTM">
        </div>
        <div class="form-input">
            <label><h4>Glosa o detalle de multa</h4></label>
            <textarea   style="height: 300px;" class="form-control" type="text" id="glosa" name="glosa">
            </textarea>
        </div>
        <br>
        <div class="form-input">
            <label><h4>Estado de multa</h4></label>
            <p>
            <input type="radio" name="statusMulta" value="CURSADA" required> Multa Cursada <br>
            <input type="radio" name="statusMulta" value="NOTIFICADA"> Multa Notificada <br>
            <input type="radio" name="statusMulta" value="IMPUGNADA"> Multa Impugnada <br>
            <input type="radio" name="statusMulta" value="APELADA"> Multa Apelada <br>
            <input type="radio" name="statusMulta" value="EJECUTADA"> Multa Ejecutada <br>
        </p>
        </div>
        <div class="container-logo">
            <button class="ingresar" type="submit">INGRESAR</button>
        </div>
        
    </form>
</div>

<div class="container-logo">
    <a href="/user/dashboarduser">
        <div class="ingresar">
            VOLVER
        </div>
    </a>
</div>






{% endblock %}

app-gest-contr/app/user/templates/usrcontrato.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-2">
            <a href="/user/usrmulta/{{ modelo_contrato.id }}">
                <div class=accion>
                    <img class="iconos-botones" src="{{ url_for('static',filename='/img/multa-white.png' ) }}">
                    <h3>Registrar Sanción</h3>

                </div>

            </a>
        </div>

        <div class="col-2">
            <a href="/user/usrfactura/{{ modelo_contrato.id }}">
                <div class=accion>
                    <img class="iconos-botones" src="{{ url_for('static',filename='/img/factura-white.png' ) }}">
                    <h3>Registrar Factura</h3>

                </div>

            </a>
        </div>
        
    </div>
</div>

<br>
<hr><br>

<h1 style="text-align: center;">Detalle Contrato</h1>
<div class="container-contrato">
    
    <div  class="atributos">
        <label><h4>CONTRATO</h4>  </label> 
        <br>
        {{ modelo_contrato.tituloContrato }} 
    </div>
    <div  class="atributos">
        <br>
        <label><h4>ID</h4>  </label> 
        <br>
        {{ modelo_contrato.idContrato }} 
    </div>
    <div  class="atributos">
        <br>
        <label><h4>VENCIMIENTO</h4>  </label> 
        <br>
        {{ modelo_contrato.fechaFinContrato }} 
    </div>
    <hr>
    <div class="atributos">
        <label> <h4> ITS/ITO RESPONSABLE </h4> </label> 
        <br>
        {{ its.nombresUser  }} {{ its.apellidosUser }}
    </div>
    <br>
    <hr>
    <br>
    <div  style="text-align: center; " class="row">
        <div class="col">
            <label>  <h4>RAZON SOCIAL</h4> </label> 
            <br>
            {{ modelo_contrato.razonSocial }} 
        </div>
        <div class="col">
            <label> <h4>DOMICILIO</h4> </label> 
            <br>
            {{ modelo_contrato.domicilioRazonSocial }} 
        </div>
        <div class="col">
            <label> <h4>RUT</h4> </label> 
            <br>
            {{ modelo_contrato.rutRazonSocial }} 
        </div>
        <br>
    </div>
    <br>
    <div  style="text-align: center;" class="row">
        <div class="col">
            <label> <h4>REPRESENTANTE LEGAL</h4> </label> 
            <br>
            {{ modelo_contrato.nombreContratante }} 
        </div>
        <div class="col">
            <label> <h4>EMAIL FIRMANTE</h4> </label> 
            <br>
            {{ modelo_contrato.emailFirmante }} 
        </div>
        <div class="col">
            <label> <h4>CI</h4> </label> 
            <br>
            {{ modelo_contrato.rutContratante }} 
        </div>
        <br>
    </div>

   
    <br>
    <hr>
    <br>
    <div class="atributos">
        <label><h4>LABORES</h4> </label> 
        <br>
        {{ modelo_contrato.labores }} 
    </div>
    <br>
    
    <br>
    <hr>
    <br>

    <div  style="text-align: center;" class="row">

        <div class="col">
            <label> <h4>MONTO</h4> </label> 
            <br>
           ${{ modelo_contrato.montoRemuneracion }} 
        </div>
        
        <div class="col">
            <label> <h4>PERIODO</h4> </label> 
            <br>
            {{ modelo_contrato.periodoPago }} horas
        </div>
        <div class="col">
            <label> <h4>DURACIÓN JORNADA </h4> </label> 
            <br>
            {{ modelo_contrato.duracionJornada }} horas
        </div>
        <div class="col">
            <label> <h4>DISTRIBUCIÓN JORNADA</h4></label> 
            <br>
            {{ modelo_contrato.distribucionJornada }} 
        </div>
        


    </div>
    
    <br>
    <hr>
    <br>
    <div style="text-align: center;" class=row>
        <div class="col">
            <a href="/admin/download/{{ 'OE_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR OFERTA ECONÓMICA</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'OT_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR OFERTA TÉCNICA</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'BA_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR BASES ADMINISTRATIVAS</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'BT_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR BASES TÉCNICAS</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'CON_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR CONSULTAS</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'GAR_'~modelo_contrato.rutContratante }}">
                <div class="descarga">DESCARGAR GARANTÍAS</div>  
            </a>
        </div>
        <div class="col">
            <a href="/admin/download/{{ 'IG_'~modelo_contrato.rutContratante }}">
                <div class="descarga">INFORMACIÓN GENERAL</div>  
            </a>
        </div>


    </div>


</div>
       
        
       
       

    </div>
    <a href="/user/dashboarduser">
        <div class="button">
            VOLVER
        </div>
    </a>




<!--
    <div class="tabla-archivos">
        <a href="/admin/download/{{ 'OE_'~modelo_contrato.rutContratante }}">Descargar Oferta Económica</a>
        <a href="/admin/download/{{ 'OT_'~modelo_contrato.rutContratante }}">Descargar Oferta Técnica</a>
        <a href="/admin/download/{{ 'BA_'~modelo_contrato.rutContratante }}">Descargar Bases Administrativas</a>
        <a href="/admin/download/{{ 'BT_'~modelo_contrato.rutContratante }}">Descargar Bases Técnicas</a>
        <a href="/admin/download/{{ 'CON_'~modelo_contrato.rutContratante }}">Descargar Consultas</a>
        <a href="/admin/download/{{ 'GAR_'~modelo_contrato.rutContratante }}">Descargar Garantías</a>
        <a href="/admin/download/{{ 'IG_'~modelo_contrato.rutContratante }}">Descargar Información General</a>

    </div>
    <a href="/user/dashboarduser">Volver </a>
-->

    {% endblock %}

app-gest-contr/app/user/templates/usrseguircontratos.html
{% extends 'layout.html' %}

{% block body %}

<br>
<!--
<div class="container">
    <div class="row">
        <div class="col">
            <a href="/user/usrmulta/{{ current_user.id }}">
                <div class=accion>
                    <img class="iconos-botones" src="{{ url_for('static',filename='/img/multa-white.png' ) }}">
                    <h3>Registrar Sanción</h3>

                </div>

            </a>
        </div>

        <div class="col">
            <a href="/user/usrfactura/{{ current_user.id }}">
                <div class=accion>
                    <img class="iconos-botones" src="{{ url_for('static',filename='/img/factura-white.png' ) }}">
                    <h3>Registrar Factura</h3>

                </div>

            </a>
        </div>

    </div>
</div>

<br>
<hr><br>


-->

<h1 style="text-align: center;">Tus Contratos</h1>

<div class="container">
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th> Contrato</th>
                <th> Vencimiento </th>
                <th> Razon Social </th>
                <th> acciones </th>

            </tr>
        </thead>


        <tbody>
            {% for contrato in total_contratos %}
            <tr>

                <td>{{ contrato.tituloContrato}} </td>
                <td> {{contrato.fechaFinContrato}} </td>
                <td> {{contrato.razonSocial }}</td>
                <td>
                    <a href="/user/usrcontrato/{{ contrato.id }}">
                        <div class="btn btn-info">
                            Seguir Contrato
                        </div>
                    </a>


                </td>

            </tr>
            {% endfor %}
        </tbody>

    </table>


</div>




<h1 style="text-align: center;">Multas Emitidas </h1>

<div class="container">
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Glosa o Descripción de Multa</th>
                <th>Monto</th>
                <th>Estado de la Multa </th>
                <th>Acción</th>
            </tr>
        </thead>

        <tbody>
            {% if total_multas %}
            {% for multa in total_multas %}
            <tr>
                <td> {{ multa.glosa }} </td>
                <td> {{ multa.monto }} UTM</td>
                <td> {{ multa.statusMulta }}</td>
                <td>
                    <a href="/user/editarmulta/{{ multa.id }}">
                        <div class="btn btn-warning">
                            Cambiar Estado
                        </div>
                    </a>
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <tr>
                <td> <h4>No existen registros</h4> </td>
                <td>  </td>
                <td></td>
                <td></td>
            </tr>
            {% endif %}

        </tbody>


    </table>

</div>

<h1 style="text-align: center;">Facturas Registradas</h1>

<div class="container">

    <table class="table">

        <thead class="thead-light">
            <tr>
                <th>Número de Factura</th>
                <th>Estado </th>
                <th>Acción </th>

            </tr>
        </thead>

        <tbody>
            {% for factura in total_facturas %}
            

            <tr>
                <td> {{factura.docFactura}} </td>
                <td> {{factura.statusFactura}} </td>
                <td> <a href="/user/editarfactura/{{ factura.id }}">
                        <div class="btn btn-warning">
                            Cambiar Estado
                        </div>
                    </a>
                </td>

            </tr>
            {% endfor %}

        </tbody>

    </table>


</div>

<h1 style="text-align: center;">Tu Actividad</h1>
<div class="container">
    <table class="table">

        <thead class="thead-light">
            <tr>
                <th>Actividad</th>

            </tr>

        </thead>

        <tbody>

            {% for log in total_logs %}

            <tr>
                <td> {{log.logUser}} </td>

            </tr>

            {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}